# Generated by Django 4.2.11 on 2024-04-13 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Autor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('data_publicacao', models.DateField(blank=True)),
                ('n_paginas', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro_Autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Autor.autor')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Livro.livro')),
            ],
        ),
    ]
