# Generated by Django 4.2.11 on 2024-04-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_rename_pais_id_usuario_pais_remove_usuario_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
