# Generated by Django 4.2.11 on 2024-04-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='died_in',
            field=models.DateField(blank=True, null=True),
        ),
    ]
