# Generated by Django 4.2.11 on 2024-04-13 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('descricao', models.TextField()),
                ('data_avaliacao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_comentario', models.DateTimeField()),
                ('avaliacao_comentada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.avaliacao')),
            ],
        ),
    ]
