# Generated by Django 4.2.11 on 2024-04-13 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='data_avaliacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
