# Generated by Django 4.2.11 on 2024-04-13 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Genero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero_favorito',
            name='Usuario_Genero_Favorito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
