# Generated by Django 4.2.11 on 2024-04-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Genero', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genero_Favorito',
        ),
    ]
