# Generated by Django 4.2.11 on 2024-04-19 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autor', '0002_alter_autor_died_in'),
        ('Genero', '0003_delete_genero_favorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero_Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Autor_Genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Autor.autor')),
                ('Genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Genero.generos')),
            ],
        ),
    ]
